### ISSUE TITLE
Home Assistant 2023.6.0 upgrades Python to 3.11. Breaks loading.

### ISSUE THREAD

**Issue by erifre** [DSorlov/swemail#23]
In the beta released for the [2023.6.0 version](https://rc.home-assistant.io/blog/2023/05/31/release-20236/) of Home Assistant, this module can no longer be loaded. Please see trace below.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/swemail/__init__.py", line 20, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

**Comment by HakanP** [comment]
This is what it shows in the Home Assistant Core log:
2023-06-04 21:15:39.615 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.swemail
File "/config/custom_components/swemail/__init__.py", line 20, in <module>
2023-06-04 21:15:39.618 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration swemail: Unable to import component: Exception importing custom_components.swemail

**Comment by thulin82** [comment]
Looks like the decorator "@asyncio.coroutine" has been deprecated since Python 3.8, and finally removed in 3.11
https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines

Since all coroutines in `__init.py__` is already marked as async, then I guess, the fix is to remove the decoration?
=> Remove row 20 from `custom_components/swemail/__init__.py`

**Comment by henrikbla** [comment]
I can confirm the component no longer works with the latest official release 2023.6 either.

**Comment by Steffe2** [comment]
> 

Tried it, seems to work for me 😁

**Comment by Steffe2** [comment]
> I've added a PR (#24) that removes the decorator. But like I state in the PR, could use some more testing

Tried that PR change, seems to work for me 😁

**Comment by ticstyle** [comment]
I had the same issue after upgrading to 2023.06.0
I commented out line 20 in the __init__.py file as suggested and restarted HA. It now works fine again, thanks! 👍

**Comment by mikaabra** [comment]
Can also confirm that commenting out line 20 makes it work fine again on 2023.6.1.
