### PR TITLE
Removed deprecated decorator @asyncio.coroutine

### LINKED ISSUE #23: Home Assistant 2023.6.0 upgrades Python to 3.11. Breaks loading.
In the beta released for the [2023.6.0 version](https://rc.home-assistant.io/blog/2023/05/31/release-20236/) of Home Assistant, this module can no longer be loaded. Please see trace below.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/swemail/__init__.py", line 20, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

### PR DESCRIPTION
**Pull request by thulin82**
https://docs.python.org/3.10/library/asyncio-task.html#generator-based-coroutines

Support for generator-based coroutines is deprecated and is removed in Python 3.11.

Fixes #23 (i hope)

Could use some more testing

### CODE REVIEW

**Review by angarok — APPROVED** [review]
This fixes the issue for me. Nice work!

**Comment by linux169** [comment]
It fixed the problem for me aswell but took awhile to start and got this error in the logs don't know if it's related

fetch data failed : HTTPSConnectionPool(host='postnummersok.citymail.se', port=443): Max retries exceeded with url: /?search="censored" (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f780a4568d0>, 'Connection to postnummersok.citymail.se timed out. (connect timeout=None)'))

**Review by ticstyle — APPROVED** [review]
Can confirm that this fixes the issue and I get no errors in the logs. 

Update: 
Works fine in 2023.06.1 too 👍

**Comment by mikaabra** [comment]
Can confirm that commenting out line 20 makes it work again on 2023.6.1.

**Review by mikaabra — APPROVED** [review]
Have tested, makes this work on 2023.6.1 again.
